/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcode/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarcodeProduct"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeNameRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KitchenInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/archive/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KitchenInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kitchen/members/{memberId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memberId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KitchenInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InviteInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KitchenInfo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    since: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPullResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncPushRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPushResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/foods/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoodEnrichRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoodEnrichResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/recipes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecipeGenerateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeDraft"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInviteRequest: {
            bringMine: boolean;
        };
        AiStatus: {
            configured: boolean;
        };
        ArchiveSummary: {
            /** Format: int32 */
            recipes: number;
            /** Format: int32 */
            mealPlans: number;
            /** Format: int32 */
            shoppingLists: number;
            /** Format: int32 */
            pantryItems: number;
        };
        BarcodeProduct: {
            barcode: string;
            name: null | string;
            brand: null | string;
            values: components["schemas"]["NutritionValues"];
        };
        ChangeEmailRequest: {
            newEmail: string;
            currentPassword: string;
        };
        ChangeNameRequest: {
            displayName: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ConfirmEmailRequest: {
            /** Format: uuid */
            userId: string;
            email: string;
            token: string;
        };
        DayPlan: {
            /** Format: date */
            date: string;
            /** Format: uuid */
            mealPlanId: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        DraftIngredient: {
            /** Format: uuid */
            foodId: string;
            /** Format: double */
            grams: number;
        };
        Food: {
            name: string;
            nameEn: null | string;
            brand: null | string;
            barcode: null | string;
            category: string;
            /** Format: double */
            kcal: number;
            /** Format: double */
            proteinG: number;
            /** Format: double */
            carbsG: number;
            /** Format: double */
            fatG: number;
            /** Format: double */
            fiberG: number;
            /** Format: double */
            sodiumMg: number;
            /** Format: double */
            unitWeightG: null | number;
            glycemicGrade: null | string;
            gradesReason: null | string;
            estimatedFields: string[];
            source: string;
            /** Format: uuid */
            photoId: null | string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        FoodEnrichRequest: {
            name: null | string;
            nameEn: null | string;
            brand: null | string;
            values: components["schemas"]["NutritionValues"];
            labelImageDataUrl: null | string;
        };
        FoodEnrichResponse: {
            name: string;
            nameEn: string;
            /** Format: double */
            kcal: number;
            /** Format: double */
            proteinG: number;
            /** Format: double */
            carbsG: number;
            /** Format: double */
            fatG: number;
            /** Format: double */
            fiberG: number;
            /** Format: double */
            sodiumMg: number;
            estimatedFields: string[];
            category: string;
            glycemicGrade: string;
            reason: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        InviteCreated: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        InviteInfo: {
            members: string[];
            /** Format: date-time */
            expiresAt: string;
        };
        JournalEntry: {
            /** Format: date */
            date: string;
            mealLabel: string;
            /** Format: uuid */
            mealItemId: null | string;
            kind: string;
            /** Format: uuid */
            variantId: null | string;
            /** Format: double */
            servings: null | number;
            /** Format: uuid */
            foodId: null | string;
            /** Format: double */
            grams: null | number;
            name: string;
            /** Format: double */
            kcal: number;
            /** Format: double */
            proteinG: number;
            /** Format: double */
            carbsG: number;
            /** Format: double */
            fatG: number;
            /** Format: double */
            fiberG: number;
            /** Format: double */
            sodiumMg: number;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        JsonElement: unknown;
        KitchenInfo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerId: null | string;
            members: components["schemas"]["KitchenMember"][];
            archive: null | components["schemas"]["ArchiveSummary"];
        };
        KitchenMember: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        LeaveResult: {
            hasArchive: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MacroBudget: {
            /** Format: double */
            kcal: number;
            /** Format: double */
            proteinG: number;
            /** Format: double */
            carbsG: number;
            /** Format: double */
            fatG: number;
        };
        Meal: {
            /** Format: uuid */
            id: string;
            label: string;
            items: components["schemas"]["MealItem"][];
        };
        MealItem: {
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: uuid */
            variantId: null | string;
            /** Format: double */
            servings: null | number;
            /** Format: uuid */
            foodId: null | string;
            /** Format: double */
            grams: null | number;
        };
        MealPlan: {
            name: string;
            meals: components["schemas"]["Meal"][];
            /** Format: uuid */
            kitchenId: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: string;
        };
        MissingIngredient: {
            name: string;
            /** Format: double */
            grams: number;
        };
        NutritionValues: {
            /** Format: double */
            kcal: null | number;
            /** Format: double */
            proteinG: null | number;
            /** Format: double */
            carbsG: null | number;
            /** Format: double */
            fatG: null | number;
            /** Format: double */
            fiberG: null | number;
            /** Format: double */
            sodiumMg: null | number;
        };
        PantryItem: {
            /** Format: uuid */
            foodId: string;
            /** Format: uuid */
            kitchenId: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        Recipe: {
            name: string;
            instructions: string;
            /** Format: int32 */
            prepTimeMin: null | number;
            difficulty: string;
            /** Format: uuid */
            photoId: null | string;
            ingredientFoodIds: string[];
            /** Format: uuid */
            kitchenId: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        RecipeDraft: {
            name: string;
            instructions: string;
            /** Format: int32 */
            prepTimeMin: number;
            difficulty: string;
            /** Format: int32 */
            servings: number;
            ingredients: components["schemas"]["DraftIngredient"][];
            missing: components["schemas"]["MissingIngredient"][];
        };
        RecipeGenerateRequest: {
            prompt: string;
            /** Format: double */
            maxKcalPerServing: null | number;
            remaining: null | components["schemas"]["MacroBudget"];
        };
        RecipeVariant: {
            /** Format: uuid */
            recipeId: string;
            name: string;
            /** Format: int32 */
            servings: number;
            ingredients: components["schemas"]["VariantIngredient"][];
            /** Format: uuid */
            kitchenId: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        RegisterRequest: {
            token: string;
            email: string;
            displayName: string;
            password: string;
        };
        ResetPasswordRequest: {
            email: string;
            token: string;
            password: string;
        };
        ShoppingList: {
            name: string;
            plans: components["schemas"]["ShoppingListPlan"][];
            checkedKeys: string[];
            /** Format: uuid */
            kitchenId: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        ShoppingListPlan: {
            /** Format: uuid */
            mealPlanId: string;
            /** Format: int32 */
            days: number;
        };
        SyncChange: {
            table: string;
            op: string;
            /** Format: uuid */
            id: string;
            data: null | components["schemas"]["JsonElement"];
        };
        SyncPullResponse: {
            /** Format: int64 */
            cursor: number;
            /** Format: uuid */
            kitchenId: string;
            users: components["schemas"]["SyncUser"][];
            foods: components["schemas"]["Food"][];
            recipes: components["schemas"]["Recipe"][];
            recipeVariants: components["schemas"]["RecipeVariant"][];
            mealPlans: components["schemas"]["MealPlan"][];
            shoppingLists: components["schemas"]["ShoppingList"][];
            pantryItems: components["schemas"]["PantryItem"][];
            dayPlans: components["schemas"]["DayPlan"][];
            journalEntries: components["schemas"]["JournalEntry"][];
            userProfiles: components["schemas"]["UserProfile"][];
            weightEntries: components["schemas"]["WeightEntry"][];
        };
        SyncPushRequest: {
            changes: components["schemas"]["SyncChange"][];
        };
        SyncPushResponse: {
            /** Format: int64 */
            version: number;
            rejected: components["schemas"]["SyncRejected"][];
        };
        SyncRejected: {
            table: string;
            /** Format: uuid */
            id: string;
            reason: string;
        };
        SyncUser: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        UserProfile: {
            sex: null | string;
            /** Format: int32 */
            birthYear: null | number;
            /** Format: double */
            heightCm: null | number;
            /** Format: double */
            weightKg: null | number;
            activityLevel: null | string;
            goal: null | string;
            /** Format: double */
            goalWeightKg: null | number;
            /** Format: double */
            weeklyRateKg: null | number;
            /** Format: double */
            goalStartWeightKg: null | number;
            /** Format: date */
            goalStartDate: null | string;
            /** Format: double */
            targetKcal: null | number;
            /** Format: double */
            targetProteinG: null | number;
            /** Format: double */
            targetCarbsG: null | number;
            /** Format: double */
            targetFatG: null | number;
            /** Format: double */
            targetFiberG: null | number;
            /** Format: double */
            targetSodiumMg: null | number;
            favoriteRecipeIds: string[];
            excludedFoodIds: string[];
            excludedCategories: string[];
            excludedRecipeIds: string[];
            likedFoodIds: string[];
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
        VariantIngredient: {
            /** Format: uuid */
            foodId: string;
            /** Format: double */
            grams: number;
        };
        WeightEntry: {
            /** Format: date */
            date: string;
            /** Format: double */
            weightKg: number;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            /** Format: int64 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
