// <auto-generated />
using System;
using System.Collections.Generic;
using MacroMate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroMate.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004173155_AddAccountsAndRoles")]
    partial class AddAccountsAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sync_version");

            modelBuilder.Entity("MacroMate.Api.Data.AiUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("UserId", "Day")
                        .HasName("pk_ai_usage");

                    b.ToTable("ai_usage", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<Guid?>("ArchiveKitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("archive_kitchen_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset?>("DemoExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demo_expires_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_users_kitchen_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("MealPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_day_plans");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_day_plans_version");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_day_plans_user_id_date");

                    b.ToTable("day_plans", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs_g");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.PrimitiveCollection<List<string>>("EstimatedFields")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("estimated_fields");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision")
                        .HasColumnName("fat_g");

                    b.Property<double>("FiberG")
                        .HasColumnType("double precision")
                        .HasColumnName("fiber_g");

                    b.Property<string>("GlycemicGrade")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("glycemic_grade");

                    b.Property<string>("GradesReason")
                        .HasColumnType("text")
                        .HasColumnName("grades_reason");

                    b.Property<string>("GradesReasonEn")
                        .HasColumnType("text")
                        .HasColumnName("grades_reason_en");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision")
                        .HasColumnName("kcal");

                    b.Property<Guid?>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision")
                        .HasColumnName("protein_g");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double precision")
                        .HasColumnName("sodium_mg");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<double?>("UnitWeightG")
                        .HasColumnType("double precision")
                        .HasColumnName("unit_weight_g");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_foods");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_foods_barcode");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_foods_kitchen_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_foods_version");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.FoodReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_food_reports");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_food_reports_food_id");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_food_reports_resolved_at");

                    b.ToTable("food_reports", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CarbsG")
                        .HasColumnType("double precision")
                        .HasColumnName("carbs_g");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("FatG")
                        .HasColumnType("double precision")
                        .HasColumnName("fat_g");

                    b.Property<double>("FiberG")
                        .HasColumnType("double precision")
                        .HasColumnName("fiber_g");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<double?>("Grams")
                        .HasColumnType("double precision")
                        .HasColumnName("grams");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision")
                        .HasColumnName("kcal");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MealItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_item_id");

                    b.Property<string>("MealLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("meal_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("ProteinG")
                        .HasColumnType("double precision")
                        .HasColumnName("protein_g");

                    b.Property<double?>("Servings")
                        .HasColumnType("double precision")
                        .HasColumnName("servings");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("double precision")
                        .HasColumnName("sodium_mg");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_journal_entries_version");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_journal_entries_user_id_date");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.Kitchen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_kitchens");

                    b.ToTable("kitchens", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.KitchenInvite", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by");

                    b.HasKey("Token")
                        .HasName("pk_kitchen_invites");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_kitchen_invites_kitchen_id");

                    b.ToTable("kitchen_invites", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Meals", "MacroMate.Api.Data.MealPlan.Meals#Meal", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Items", "MacroMate.Api.Data.MealPlan.Meals#Meal.Items#MealItem", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<Guid?>("FoodId");

                                    b2.Property<double?>("Grams");

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Kind")
                                        .IsRequired();

                                    b2.Property<double?>("Servings");

                                    b2.Property<Guid?>("VariantId");
                                });

                            b1
                                .ToJson("meals")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_meal_plans");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_meal_plans_kitchen_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_meal_plans_version");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_pantry_items");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_pantry_items_version");

                    b.HasIndex("KitchenId", "FoodId")
                        .IsUnique()
                        .HasDatabaseName("ix_pantry_items_kitchen_id_food_id");

                    b.ToTable("pantry_items", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty");

                    b.PrimitiveCollection<List<Guid>>("IngredientFoodIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("ingredient_food_ids");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<int?>("PrepTimeMin")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_min");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_recipes_kitchen_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_recipes_version");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.RecipeVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .HasColumnType("integer")
                        .HasColumnName("servings");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Ingredients", "MacroMate.Api.Data.RecipeVariant.Ingredients#VariantIngredient", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("FoodId");

                            b1.Property<double>("Grams");

                            b1
                                .ToJson("ingredients")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recipe_variants");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_recipe_variants_kitchen_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_variants_recipe_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_recipe_variants_version");

                    b.ToTable("recipe_variants", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("CheckedKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("checked_keys");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("KitchenId")
                        .HasColumnType("uuid")
                        .HasColumnName("kitchen_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Plans", "MacroMate.Api.Data.ShoppingList.Plans#ShoppingListPlan", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Days");

                            b1.Property<Guid>("MealPlanId");

                            b1
                                .ToJson("plans")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_shopping_lists");

                    b.HasIndex("KitchenId")
                        .HasDatabaseName("ix_shopping_lists_kitchen_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_shopping_lists_version");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("text")
                        .HasColumnName("activity_level");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.PrimitiveCollection<List<string>>("ExcludedCategories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_categories");

                    b.PrimitiveCollection<List<Guid>>("ExcludedFoodIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("excluded_food_ids");

                    b.PrimitiveCollection<List<Guid>>("ExcludedRecipeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("excluded_recipe_ids");

                    b.PrimitiveCollection<List<Guid>>("FavoriteRecipeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("favorite_recipe_ids");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<DateOnly?>("GoalStartDate")
                        .HasColumnType("date")
                        .HasColumnName("goal_start_date");

                    b.Property<double?>("GoalStartWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("goal_start_weight_kg");

                    b.Property<double?>("GoalWeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("goal_weight_kg");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_cm");

                    b.PrimitiveCollection<List<Guid>>("LikedFoodIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("liked_food_ids");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<double?>("TargetCarbsG")
                        .HasColumnType("double precision")
                        .HasColumnName("target_carbs_g");

                    b.Property<double?>("TargetFatG")
                        .HasColumnType("double precision")
                        .HasColumnName("target_fat_g");

                    b.Property<double?>("TargetFiberG")
                        .HasColumnType("double precision")
                        .HasColumnName("target_fiber_g");

                    b.Property<double?>("TargetKcal")
                        .HasColumnType("double precision")
                        .HasColumnName("target_kcal");

                    b.Property<double?>("TargetProteinG")
                        .HasColumnType("double precision")
                        .HasColumnName("target_protein_g");

                    b.Property<double?>("TargetSodiumMg")
                        .HasColumnType("double precision")
                        .HasColumnName("target_sodium_mg");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<double?>("WeeklyRateKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weekly_rate_kg");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_user_profiles_version");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("MacroMate.Api.Data.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_weight_entries");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_weight_entries_version");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_weight_entries_user_id_date");

                    b.ToTable("weight_entries", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MacroMate.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MacroMate.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("MacroMate.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MacroMate.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
