/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppFoodsIndexRouteImport } from './routes/_app/foods/index'
import { Route as AppFoodsNewRouteImport } from './routes/_app/foods/new'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans/index'
import { Route as AppPlansPlanIdRouteImport } from './routes/_app/plans/$planId'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppRecipesGenerateRouteImport } from './routes/_app/recipes/generate'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppShoppingIndexRouteImport } from './routes/_app/shopping/index'
import { Route as AppShoppingListIdRouteImport } from './routes/_app/shopping/$listId'
import { Route as AppFoodsFoodIdIndexRouteImport } from './routes/_app/foods/$foodId/index'
import { Route as AppFoodsFoodIdEditRouteImport } from './routes/_app/foods/$foodId/edit'
import { Route as AppRecipesRecipeIdIndexRouteImport } from './routes/_app/recipes/$recipeId/index'
import { Route as AppRecipesRecipeIdEditRouteImport } from './routes/_app/recipes/$recipeId/edit'
import { Route as AppRecipesRecipeIdVariantsVariantIdRouteImport } from './routes/_app/recipes/$recipeId/variants/$variantId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFoodsIndexRoute = AppFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsNewRoute = AppFoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansPlanIdRoute = AppPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesGenerateRoute = AppRecipesGenerateRouteImport.update({
  id: '/recipes/generate',
  path: '/recipes/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingIndexRoute = AppShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingListIdRoute = AppShoppingListIdRouteImport.update({
  id: '/shopping/$listId',
  path: '/shopping/$listId',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsFoodIdIndexRoute = AppFoodsFoodIdIndexRouteImport.update({
  id: '/foods/$foodId/',
  path: '/foods/$foodId/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsFoodIdEditRoute = AppFoodsFoodIdEditRouteImport.update({
  id: '/foods/$foodId/edit',
  path: '/foods/$foodId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdIndexRoute = AppRecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdEditRoute = AppRecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdVariantsVariantIdRoute =
  AppRecipesRecipeIdVariantsVariantIdRouteImport.update({
    id: '/recipes/$recipeId/variants/$variantId',
    path: '/recipes/$recipeId/variants/$variantId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/invite/$token': typeof InviteTokenRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/recipes/generate': typeof AppRecipesGenerateRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/shopping/$listId': typeof AppShoppingListIdRoute
  '/foods/': typeof AppFoodsIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/shopping/': typeof AppShoppingIndexRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
  '/recipes/$recipeId/variants/$variantId': typeof AppRecipesRecipeIdVariantsVariantIdRoute
}
export interface FileRoutesByTo {
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/recipes/generate': typeof AppRecipesGenerateRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/shopping/$listId': typeof AppShoppingListIdRoute
  '/foods': typeof AppFoodsIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/shopping': typeof AppShoppingIndexRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/foods/$foodId': typeof AppFoodsFoodIdIndexRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdIndexRoute
  '/recipes/$recipeId/variants/$variantId': typeof AppRecipesRecipeIdVariantsVariantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/foods/new': typeof AppFoodsNewRoute
  '/_app/plans/$planId': typeof AppPlansPlanIdRoute
  '/_app/recipes/generate': typeof AppRecipesGenerateRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/shopping/$listId': typeof AppShoppingListIdRoute
  '/_app/foods/': typeof AppFoodsIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/shopping/': typeof AppShoppingIndexRoute
  '/_app/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/_app/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/_app/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/_app/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
  '/_app/recipes/$recipeId/variants/$variantId': typeof AppRecipesRecipeIdVariantsVariantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/profile'
    | '/progress'
    | '/invite/$token'
    | '/foods/new'
    | '/plans/$planId'
    | '/recipes/generate'
    | '/recipes/new'
    | '/shopping/$listId'
    | '/foods/'
    | '/plans/'
    | '/recipes/'
    | '/shopping/'
    | '/foods/$foodId/edit'
    | '/recipes/$recipeId/edit'
    | '/foods/$foodId/'
    | '/recipes/$recipeId/'
    | '/recipes/$recipeId/variants/$variantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/profile'
    | '/progress'
    | '/invite/$token'
    | '/'
    | '/foods/new'
    | '/plans/$planId'
    | '/recipes/generate'
    | '/recipes/new'
    | '/shopping/$listId'
    | '/foods'
    | '/plans'
    | '/recipes'
    | '/shopping'
    | '/foods/$foodId/edit'
    | '/recipes/$recipeId/edit'
    | '/foods/$foodId'
    | '/recipes/$recipeId'
    | '/recipes/$recipeId/variants/$variantId'
  id:
    | '__root__'
    | '/_app'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/profile'
    | '/_app/progress'
    | '/invite/$token'
    | '/_app/'
    | '/_app/foods/new'
    | '/_app/plans/$planId'
    | '/_app/recipes/generate'
    | '/_app/recipes/new'
    | '/_app/shopping/$listId'
    | '/_app/foods/'
    | '/_app/plans/'
    | '/_app/recipes/'
    | '/_app/shopping/'
    | '/_app/foods/$foodId/edit'
    | '/_app/recipes/$recipeId/edit'
    | '/_app/foods/$foodId/'
    | '/_app/recipes/$recipeId/'
    | '/_app/recipes/$recipeId/variants/$variantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/foods/': {
      id: '/_app/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof AppFoodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/new': {
      id: '/_app/foods/new'
      path: '/foods/new'
      fullPath: '/foods/new'
      preLoaderRoute: typeof AppFoodsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/$planId': {
      id: '/_app/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AppPlansPlanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/generate': {
      id: '/_app/recipes/generate'
      path: '/recipes/generate'
      fullPath: '/recipes/generate'
      preLoaderRoute: typeof AppRecipesGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping/': {
      id: '/_app/shopping/'
      path: '/shopping'
      fullPath: '/shopping/'
      preLoaderRoute: typeof AppShoppingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping/$listId': {
      id: '/_app/shopping/$listId'
      path: '/shopping/$listId'
      fullPath: '/shopping/$listId'
      preLoaderRoute: typeof AppShoppingListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/$foodId/': {
      id: '/_app/foods/$foodId/'
      path: '/foods/$foodId'
      fullPath: '/foods/$foodId/'
      preLoaderRoute: typeof AppFoodsFoodIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/$foodId/edit': {
      id: '/_app/foods/$foodId/edit'
      path: '/foods/$foodId/edit'
      fullPath: '/foods/$foodId/edit'
      preLoaderRoute: typeof AppFoodsFoodIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/': {
      id: '/_app/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/edit': {
      id: '/_app/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/variants/$variantId': {
      id: '/_app/recipes/$recipeId/variants/$variantId'
      path: '/recipes/$recipeId/variants/$variantId'
      fullPath: '/recipes/$recipeId/variants/$variantId'
      preLoaderRoute: typeof AppRecipesRecipeIdVariantsVariantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFoodsNewRoute: typeof AppFoodsNewRoute
  AppPlansPlanIdRoute: typeof AppPlansPlanIdRoute
  AppRecipesGenerateRoute: typeof AppRecipesGenerateRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppShoppingListIdRoute: typeof AppShoppingListIdRoute
  AppFoodsIndexRoute: typeof AppFoodsIndexRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppShoppingIndexRoute: typeof AppShoppingIndexRoute
  AppFoodsFoodIdEditRoute: typeof AppFoodsFoodIdEditRoute
  AppRecipesRecipeIdEditRoute: typeof AppRecipesRecipeIdEditRoute
  AppFoodsFoodIdIndexRoute: typeof AppFoodsFoodIdIndexRoute
  AppRecipesRecipeIdIndexRoute: typeof AppRecipesRecipeIdIndexRoute
  AppRecipesRecipeIdVariantsVariantIdRoute: typeof AppRecipesRecipeIdVariantsVariantIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppIndexRoute: AppIndexRoute,
  AppFoodsNewRoute: AppFoodsNewRoute,
  AppPlansPlanIdRoute: AppPlansPlanIdRoute,
  AppRecipesGenerateRoute: AppRecipesGenerateRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppShoppingListIdRoute: AppShoppingListIdRoute,
  AppFoodsIndexRoute: AppFoodsIndexRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppShoppingIndexRoute: AppShoppingIndexRoute,
  AppFoodsFoodIdEditRoute: AppFoodsFoodIdEditRoute,
  AppRecipesRecipeIdEditRoute: AppRecipesRecipeIdEditRoute,
  AppFoodsFoodIdIndexRoute: AppFoodsFoodIdIndexRoute,
  AppRecipesRecipeIdIndexRoute: AppRecipesRecipeIdIndexRoute,
  AppRecipesRecipeIdVariantsVariantIdRoute:
    AppRecipesRecipeIdVariantsVariantIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
